version: '3.8'

services:
  spring-app:
    image: sistemacontable:1.0
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/sistemacontable  # Cambiar el puerto a 3308
      SPRING_DATASOURCE_USERNAME: angel
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - my-network

networks:
  my-network:
    external: true
