version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: sistemacontable
      MYSQL_USER: angel
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
